// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codebox} from '../models';

export function CreateEd25519KeyPair(arg1:string):Promise<codebox.KeyPair>;

export function Greet(arg1:string):Promise<string>;
