// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AesGCMEncrypt(arg1, arg2, arg3) {
  return window['go']['main']['App']['AesGCMEncrypt'](arg1, arg2, arg3);
}

export function CreateEd25519KeyPair(arg1) {
  return window['go']['main']['App']['CreateEd25519KeyPair'](arg1);
}

export function CreateRSAKeyPair(arg1) {
  return window['go']['main']['App']['CreateRSAKeyPair'](arg1);
}

export function CreateSHA1MD5Hash(arg1) {
  return window['go']['main']['App']['CreateSHA1MD5Hash'](arg1);
}

export function CreateSHA2Hash(arg1) {
  return window['go']['main']['App']['CreateSHA2Hash'](arg1);
}

export function CreateSHA3Hash(arg1) {
  return window['go']['main']['App']['CreateSHA3Hash'](arg1);
}

export function CreateX25519KeyPair() {
  return window['go']['main']['App']['CreateX25519KeyPair']();
}

export function Ed25519Sign(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Ed25519Sign'](arg1, arg2, arg3, arg4);
}

export function Ed25519Verify(arg1, arg2, arg3) {
  return window['go']['main']['App']['Ed25519Verify'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
